
/* Tabla: tipousuario*/
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (1, 'Administrador', 1);
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (2, 'Dominio', 1);
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (3, 'Grupo', 1);
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (4, 'Comercializadora', 1);
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (5, 'Agencia', 1);
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (6, 'Taquilla', 1);
INSERT INTO tb_tipousuario (ID_TIPOUSUARIO, DESCRIPCION, ESTATUS) VALUES (7, 'Apostador', 1);

/* Tabla: tipojuego*/
INSERT INTO tb_tipojuego (ID_TIPOJUEGO, DESCRIPCION, PAGINA, ESTATUS) VALUES (1, 'Ruleta', 'ruleta.aspx', 1);
INSERT INTO tb_tipojuego (ID_TIPOJUEGO, DESCRIPCION, PAGINA, ESTATUS) VALUES (2, 'Tripleta', 'tripleta.aspx', 1);


/* Tabla: opcionmenu*/
INSERT INTO tb_opcionmenu (ID_OPCIONMENU, ID_OPCIONMENUPADRE, NOMBRE, DESCRIPCION, URL, POSICION, ESTATUS) VALUES (1, NULL, 'Inicio', 'Opcion 1', 'home', 1000, 1);
INSERT INTO tb_opcionmenu (ID_OPCIONMENU, ID_OPCIONMENUPADRE, NOMBRE, DESCRIPCION, URL, POSICION, ESTATUS) VALUES (2, NULL, 'Administración Dominios', 'Opcion 2', 'domain', 1500, 1);
INSERT INTO tb_opcionmenu (ID_OPCIONMENU, ID_OPCIONMENUPADRE, NOMBRE, DESCRIPCION, URL, POSICION, ESTATUS) VALUES (3, NULL, 'Administración Usuarios Internos', 'Opcion3', 'internal-users', 1600, 1);
INSERT INTO tb_opcionmenu (ID_OPCIONMENU, ID_OPCIONMENUPADRE, NOMBRE, DESCRIPCION, URL, POSICION, ESTATUS) VALUES (4, NULL, 'Administración Juegos', 'Opcion 4', 'games', 1900, 1);
INSERT INTO tb_opcionmenu (ID_OPCIONMENU, ID_OPCIONMENUPADRE, NOMBRE, DESCRIPCION, URL, POSICION, ESTATUS) VALUES (5, NULL, 'Administración Impuestos', 'Opcion 5', 'taxes', 2000, 1);

/* Tabla: dia*/
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (1, 'LUNES', 1);
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (2, 'MARTES', 1);
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (3, 'MIERCOLES', 1);
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (4, 'JUEVES', 1);
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (5, 'VIERNES', 1);
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (6, 'SABADO', 1);
INSERT INTO tb_dia (ID_DIA, NOMBRE, ESTATUS) VALUES (7, 'DOMINGO', 1);

INSERT INTO tb_tipousuario_opcionmenu (ID_OPCIONMENU, ID_TIPOUSUARIO, ESTATUS) VALUES (1, 7, 1);

SELECT A.NOMBRE, A.DESCRIPCION, A.URL, A.POSICION, A.ESTATUS FROM TB_OPCIONMENU AS A JOIN TB_TIPOUSUARIO_OPCIONMENU AS B WHERE (B.ID_TIPOUSUARIO = 7) AND (A.ID_OPCIONMENU = B.ID_OPCIONMENU);

SELECT * FROM tb_usuario;
delete from tb_usuario where nombre='Pedro';