tb_tipousuario_opcionmenuID_OPCIONMENUPADREID_OPCIONMENUPADRECREATE SCHEMA IF NOT EXISTS `LotoUCAB` DEFAULT CHARACTER SET utf8 ;
USE `LotoUCAB` ;

CREATE TABLE TB_APERTURA (
  `ID_APERTURA` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `FECHA_APERTURA` datetime(3) DEFAULT (now()) NULL,
  `FECHA_CIERRE` datetime(3) NULL,
  `MONTO_APERTURA` decimal(15,4) DEFAULT ((0)) NOT NULL,
  `MONTO_CIERRE` decimal(15,4) DEFAULT ((0)) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_APERTURA`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_AUDITORIA (
  `ID_AUDITORIA` int AUTO_INCREMENT NOT NULL,
  `ID_EVENTO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `FECHA_HORA` datetime(3) DEFAULT (now()) NOT NULL,
  `PARAMETROS` varchar(5000) NOT NULL,
  `EXITO` tinyint NOT NULL,
   PRIMARY KEY (`ID_AUDITORIA`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_COMISION (
  `ID_COMISION` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `COMISIONVENTA` decimal(18,2) NULL,
  `COMISIONPARTICIPACION` decimal(18,2) NULL,
  `FECHAINICIO` datetime(3) NOT NULL,
  `FECHAFIN` datetime(3) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_COMISION`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_CONJUNTO (
  `ID_CONJUNTO` int AUTO_INCREMENT NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `MONTO` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_CONJUNTO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_CONJUNTO_ITEM (
  `ID_CONJUNTOITEM` int AUTO_INCREMENT NOT NULL,
  `ID_ITEM` int NOT NULL,
  `ID_CONJUNTO` int NOT NULL,
  `CUPO_MAX` int NULL,
  `MONTO_MAX` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_CONJUNTOITEM`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_DIA (
  `ID_DIA` int AUTO_INCREMENT NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_DIA`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;



CREATE TABLE TB_DIA_SORTEO (
  `ID_DIASORTEO` int AUTO_INCREMENT NOT NULL,
  `ID_DIA` int NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_DIASORTEO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_DISPONIBLE_USUARIO_SORTEO_ITEM (
  `ID_DISPONIBLEUSUARIOSORTEOITEM` int AUTO_INCREMENT NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `ID_ITEM` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CUPO_DISPONIBLE` int NOT NULL,
  `MONTO_DISPONIBLE` decimal(15,4) NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_DISPONIBLEUSUARIOSORTEOITEM`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_DOMINIO (
  `ID_DOMINIO` int AUTO_INCREMENT NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `NUMEROIDENTIFICACION` varchar(50) NOT NULL,
  `ESTATUS` int NOT NULL,
  `DIRECCION` varchar(500) NULL,
  `TELEFONO` varchar(10) NULL,
  `BANQUEO` tinyint NULL,
  `PORCENTAJE` decimal(18,2) NULL,
   PRIMARY KEY (`ID_DOMINIO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_DOMINIO_IMPUESTO (
  `ID_DOMINIOIMPUESTOS` int AUTO_INCREMENT NOT NULL,
  `ID_IMPUESTO` int NOT NULL,
  `ID_DOMINIO` int NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_DOMINIOIMPUESTOS`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_EVENTO (
  `ID_EVENTO` int AUTO_INCREMENT NOT NULL,
  `DESCRIPCION` varchar(50) NULL,
  `ESTATUS` int NULL,
  `COD_EVENTO` int NULL,
   PRIMARY KEY (`ID_EVENTO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_IMPUESTO (
  `ID_IMPUESTO` int AUTO_INCREMENT NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `APLICASOBRE` char(1) NOT NULL,
  `PORCENTAJE` decimal(4,2) NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_IMPUESTO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_ITEM (
  `ID_ITEM` int AUTO_INCREMENT NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `NOMBRE` varchar(50) NULL,
  `VALOR` varchar(4) NOT NULL,
  `CUPO` int NULL,
  `MONTO` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_ITEM`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_JUEGO (
  `ID_JUEGO` int AUTO_INCREMENT NOT NULL,
  `ID_TIPOJUEGO` int NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `ESTATUS` int NOT NULL,
  `FACTORPAGO` int NULL,
  `TIEMPOCIERRE` int NULL,
   PRIMARY KEY (`ID_JUEGO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_JUGADA (
  `ID_JUGADA` int AUTO_INCREMENT NOT NULL,
  `ID_TICKET` int NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `ID_ITEM` int NULL,
  `ID_CONJUNTO` int NULL,
  `MONTO_APUESTA` decimal(15,4) NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_JUGADA`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;

CREATE TABLE TB_MONEDERO (
  `ID_OPERACION` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `MONTO` decimal(15,4) NULL,
  `ID_TIPOOPERACION` int NOT NULL,
  `ESTATUS` int NOT NULL,
  `FECHA_HORA` datetime(3) NULL,
  `DESCRIPCION` varchar(150) NULL,
   PRIMARY KEY (`ID_OPERACION`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
   
   
CREATE TABLE TB_OPCIONMENU (
  `ID_OPCIONMENU` int AUTO_INCREMENT NOT NULL,
  `ID_OPCIONMENUPADRE` int NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `URL` varchar(200) NULL,
  `POSICION` int NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_OPCIONMENU`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_RESULTADO (
  `ID_RESULTADO` int AUTO_INCREMENT NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `ID_ITEM` int NOT NULL,
  `FECHA_HORA` datetime(3) DEFAULT (now()) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_RESULTADO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;



CREATE TABLE TB_SOLICITUD (
  `ID_SOLICITUD` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `MONTO` decimal(15,4) NULL,
  `ID_TIPOOPERACION` int NOT NULL,
  `CODIGOQR` varchar(50) NOT NULL,
  `CODIGOSOLICITUD` varchar(10) NOT NULL,
  `FECHA_HORA` datetime(3) NULL,
  `ESTATUS` int NULL,
   PRIMARY KEY (`ID_SOLICITUD`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;

 

CREATE TABLE TB_SORTEO (
  `ID_SORTEO` int AUTO_INCREMENT NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `HORA` time(6) NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_SORTEO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_SORTEO_ITEM (
  `ID_SORTEOITEM` int AUTO_INCREMENT NOT NULL,
  `ID_ITEM` int NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `CUPO` int NULL,
  `MONTO` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_SORTEOITEM`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_TICKET (
  `ID_TICKET` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `SERIAL` varchar(150) NOT NULL,
  `FECHA_HORA` datetime(3) NOT NULL,
  `ESTATUS` int NOT NULL,
  `MONTO_PAGADO` decimal(15,4) DEFAULT ((0)) NULL,
  `FECHA_HORA_PAGO` datetime(3) NULL,
  `MONTO_APUESTA` decimal(15,4) NULL,
   PRIMARY KEY (`ID_TICKET`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_TIPOJUEGO (
  `ID_TIPOJUEGO` int AUTO_INCREMENT NOT NULL,
  `DESCRIPCION` varchar(50) NULL,
  `PAGINA` varchar(150) NULL,
  `ESTATUS` int NULL,
   PRIMARY KEY (`ID_TIPOJUEGO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
   
   
CREATE TABLE TB_TIPOOPERACION (
  `ID_TIPOOPERACION` int AUTO_INCREMENT NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `OPERACION` char(1) NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_TIPOOPERACION`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
  

CREATE TABLE TB_TIPOUSUARIO (
  `ID_TIPOUSUARIO` int AUTO_INCREMENT NOT NULL,
  `DESCRIPCION` varchar(50) NULL,
  `ESTATUS` int NULL,
   PRIMARY KEY (`ID_TIPOUSUARIO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_TIPOUSUARIO_OPCIONMENU (
  `ID_TIPOUSUARIOOPCIONMENU` int AUTO_INCREMENT NOT NULL,
  `ID_OPCIONMENU` int NOT NULL,
  `ID_TIPOUSUARIO` int NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_TIPOUSUARIOOPCIONMENU`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;

CREATE TABLE TB_USUARIO (
  `ID_USUARIO` int AUTO_INCREMENT NOT NULL,
  `ID_DOMINIO` int NULL,
  `ID_TIPOUSUARIO` int NOT NULL,
  `ID_USUARIOPADRE` int NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `APELLIDO` varchar(50) NOT NULL,
  `NUMEROIDENTIFICACION` varchar(50) NOT NULL,
  `USUARIO` varchar(50) NOT NULL,
  `CORREOELECTRONICO` varchar(250) NULL,
  `ESTATUS` int NOT NULL,
  `CADUCIDAD` int NULL,
  `CLAVE` nvarchar(1000) NULL,
   PRIMARY KEY (`ID_USUARIO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_USUARIO_JUEGO (
  `ID_USUARIOJUEGO` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `MAX_VENTA` decimal(15,4) NULL,
  `MAX_POSIBLE_PERDIDA` decimal(15,4) NULL,
  `MAX_TICKET_ITEM` int NULL,
  `MAX_TICKET` int NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_USUARIOJUEGO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;


CREATE TABLE TB_USUARIO_JUEGO_CONJUNTO (
  `ID_USUARIOJUEGOCONJUNTO` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `ID_CONJUNTO` int NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `MONTO_MAX` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_USUARIOJUEGOCONJUNTO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_USUARIO_JUEGO_CONJUNTO_ITEM (
  `ID_USUARIOJUEGOCONJUNTOITEM` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `ID_CONJUNTO` int NOT NULL,
  `ID_JUEGO` int NOT NULL,
  `ID_ITEM` int NOT NULL,
  `CUPO_MAX` int NULL,
  `MONTO_MAX` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
  `CUPO_DISPONIBLE` int NULL,
  `MONTO_DISPONIBLE` decimal(15,4) NULL,
   PRIMARY KEY (`ID_USUARIOJUEGOCONJUNTOITEM`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;

CREATE TABLE TB_USUARIO_OPCIONMENU (
  `ID_USUARIOOPCIONMENU` int AUTO_INCREMENT NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `ID_OPCIONMENU` int NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_USUARIOOPCIONMENU`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
   
CREATE TABLE TB_USUARIO_SORTEO (
  `ID_USUARIOSORTEO` int AUTO_INCREMENT NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `ESTATUS` int NOT NULL,
   PRIMARY KEY (`ID_USUARIOSORTEO`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;
 

CREATE TABLE TB_USUARIO_SORTEO_ITEM (
  `ID_USUARIOSORTEOITEM` int AUTO_INCREMENT NOT NULL,
  `ID_SORTEO` int NOT NULL,
  `ID_ITEM` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CUPO_MAX` int NULL,
  `MONTO_MAX` decimal(15,4) NULL,
  `ESTATUS` int NOT NULL,
  `CUPO_DISPONIBLE` int NULL,
  `MONTO_DISPONIBLE` decimal(15,4) NULL,
   PRIMARY KEY (`ID_USUARIOSORTEOITEM`))
   ENGINE = InnoDB
   AUTO_INCREMENT = 1
   DEFAULT CHARACTER SET = utf8;



-- ----------------------------
-- Foreign Keys structure for table TB_APERTURA
-- ----------------------------
ALTER TABLE `TB_APERTURA` ADD CONSTRAINT `fk_usuario_apertura` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_AUDITORIA
-- ----------------------------
ALTER TABLE `TB_AUDITORIA` ADD CONSTRAINT `fk_evento_auditoria` FOREIGN KEY (`ID_EVENTO`) REFERENCES TB_EVENTO (`ID_EVENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_AUDITORIA` ADD CONSTRAINT `fk_usuario_auditoria` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_COMISION
-- ----------------------------
ALTER TABLE `TB_COMISION` ADD CONSTRAINT `fk_usuario_comision` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_CONJUNTO
-- ----------------------------
ALTER TABLE `TB_CONJUNTO` ADD CONSTRAINT `fk_juego_conjunto` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_CONJUNTO_ITEM
-- ----------------------------
ALTER TABLE `TB_CONJUNTO_ITEM` ADD CONSTRAINT `fk_conjunto_conjuntoitem` FOREIGN KEY (`ID_CONJUNTO`) REFERENCES TB_CONJUNTO (`ID_CONJUNTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_CONJUNTO_ITEM` ADD CONSTRAINT `fk_item_conjuntoitem` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_DIA_SORTEO
-- ----------------------------
ALTER TABLE `TB_DIA_SORTEO` ADD CONSTRAINT `fk_dia_diasorteo` FOREIGN KEY (`ID_DIA`) REFERENCES TB_DIA (`ID_DIA`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_DIA_SORTEO` ADD CONSTRAINT `fk_sorteo_diasorteo` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_DISPONIBLE_USUARIO_SORTEO_ITEM
-- ----------------------------
ALTER TABLE `TB_DISPONIBLE_USUARIO_SORTEO_ITEM` ADD CONSTRAINT `fk_item_disponibleusuariosorteoitem` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_DISPONIBLE_USUARIO_SORTEO_ITEM` ADD CONSTRAINT `fk_sorteo_disponibleusuariosorteoitem` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_DISPONIBLE_USUARIO_SORTEO_ITEM` ADD CONSTRAINT `fk_usuario_disponibleusuariosorteoitem` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_DOMINIO_IMPUESTO
-- ----------------------------
ALTER TABLE `TB_DOMINIO_IMPUESTO` ADD CONSTRAINT `fk_dominio_dominioimpuesto` FOREIGN KEY (`ID_DOMINIO`) REFERENCES TB_DOMINIO (`ID_DOMINIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_DOMINIO_IMPUESTO` ADD CONSTRAINT `fk_impuesto_dominioimpuesto` FOREIGN KEY (`ID_IMPUESTO`) REFERENCES TB_IMPUESTO (`ID_IMPUESTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_ITEM
-- ----------------------------
ALTER TABLE `TB_ITEM` ADD CONSTRAINT `fk_juego_item` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_JUEGO
-- ----------------------------
ALTER TABLE `TB_JUEGO` ADD CONSTRAINT `fk_tipojuego_juego` FOREIGN KEY (`ID_TIPOJUEGO`) REFERENCES TB_TIPOJUEGO (`ID_TIPOJUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_JUGADA
-- ----------------------------
ALTER TABLE `TB_JUGADA` ADD CONSTRAINT `fk_conjunto_jugada` FOREIGN KEY (`ID_CONJUNTO`) REFERENCES TB_CONJUNTO (`ID_CONJUNTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_JUGADA` ADD CONSTRAINT `fk_item_jugada` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_JUGADA` ADD CONSTRAINT `fk_juego_jugada` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_JUGADA` ADD CONSTRAINT `fk_sorteo_jugada` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_JUGADA` ADD CONSTRAINT `fk_ticket_jugada` FOREIGN KEY (`ID_TICKET`) REFERENCES TB_TICKET (`ID_TICKET`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_MONEDERO
-- ----------------------------
ALTER TABLE `TB_MONEDERO` ADD CONSTRAINT `fk_tipooperacion_monedero` FOREIGN KEY (`ID_TIPOOPERACION`) REFERENCES TB_TIPOOPERACION (`ID_TIPOOPERACION`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_MONEDERO` ADD CONSTRAINT `fk_usuario_monedero` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_OPCIONMENU
-- ----------------------------
ALTER TABLE `TB_OPCIONMENU` ADD CONSTRAINT `fk_opcionmenu_opcionmenu` FOREIGN KEY (`ID_OPCIONMENUPADRE`) REFERENCES TB_OPCIONMENU (`ID_OPCIONMENU`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_RESULTADO
-- ----------------------------
ALTER TABLE `TB_RESULTADO` ADD CONSTRAINT `fk_item_resultado` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_RESULTADO` ADD CONSTRAINT `fk_juego_resultado` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_RESULTADO` ADD CONSTRAINT `fk_sorteo_resultado` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_SOLICITUD
-- ----------------------------
ALTER TABLE `TB_SOLICITUD` ADD CONSTRAINT `fk_tipooperacion_solicitud` FOREIGN KEY (`ID_TIPOOPERACION`) REFERENCES TB_TIPOOPERACION (`ID_TIPOOPERACION`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_SOLICITUD` ADD CONSTRAINT `fk_usuario_solicitud` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_SORTEO
-- ----------------------------
ALTER TABLE `TB_SORTEO` ADD CONSTRAINT `fk_juego_sorteo` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_SORTEO_ITEM
-- ----------------------------
ALTER TABLE `TB_SORTEO_ITEM` ADD CONSTRAINT `fk_item_sorteoitem` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_SORTEO_ITEM` ADD CONSTRAINT `fk_sorteo_sorteoitem` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_TICKET
-- ----------------------------
ALTER TABLE `TB_TICKET` ADD CONSTRAINT `fk_usuario_ticket` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_TIPOUSUARIO_OPCIONMENU
-- ----------------------------
ALTER TABLE `TB_TIPOUSUARIO_OPCIONMENU` ADD CONSTRAINT `fk_opcionmenu_tipousuarioopcionmenu` FOREIGN KEY (`ID_OPCIONMENU`) REFERENCES TB_OPCIONMENU (`ID_OPCIONMENU`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_TIPOUSUARIO_OPCIONMENU` ADD CONSTRAINT `fk_tipousuario_tipousuarioopcionmenu` FOREIGN KEY (`ID_TIPOUSUARIO`) REFERENCES TB_TIPOUSUARIO (`ID_TIPOUSUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO
-- ----------------------------
ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `fk_dominio_usuario` FOREIGN KEY (`ID_DOMINIO`) REFERENCES TB_DOMINIO (`ID_DOMINIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `fk_tipousuario_usuario` FOREIGN KEY (`ID_TIPOUSUARIO`) REFERENCES TB_TIPOUSUARIO (`ID_TIPOUSUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `fk_usuario_usuario` FOREIGN KEY (`ID_USUARIOPADRE`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO_JUEGO
-- ----------------------------
ALTER TABLE `TB_USUARIO_JUEGO` ADD CONSTRAINT `fk_juego_usuariojuego` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_JUEGO` ADD CONSTRAINT `fk_usuario_usuariojuego` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO_JUEGO_CONJUNTO
-- ----------------------------
ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO` ADD CONSTRAINT `fk_conjunto_usuariojuegoconjunto` FOREIGN KEY (`ID_CONJUNTO`) REFERENCES TB_CONJUNTO (`ID_CONJUNTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO` ADD CONSTRAINT `fk_juego_usuariojuegoconjunto` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO` ADD CONSTRAINT `fk_usuario_usuariojuegoconjunto` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO_JUEGO_CONJUNTO_ITEM
-- ----------------------------
ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO_ITEM` ADD CONSTRAINT `fk_conjunto_usuariojuegoconjuntoitem` FOREIGN KEY (`ID_CONJUNTO`) REFERENCES TB_CONJUNTO (`ID_CONJUNTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO_ITEM` ADD CONSTRAINT `fk_item_usuariojuegoconjuntoitem` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO_ITEM` ADD CONSTRAINT `fk_juego_usuariojuegoconjuntoitem` FOREIGN KEY (`ID_JUEGO`) REFERENCES TB_JUEGO (`ID_JUEGO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_JUEGO_CONJUNTO_ITEM` ADD CONSTRAINT `fk_usuario_usuariojuegoconjuntoitem` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO_OPCIONMENU
-- ----------------------------
ALTER TABLE `TB_USUARIO_OPCIONMENU` ADD CONSTRAINT `fk_opcionmenu_usuarioopcionmenu` FOREIGN KEY (`ID_OPCIONMENU`) REFERENCES TB_OPCIONMENU (`ID_OPCIONMENU`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_OPCIONMENU` ADD CONSTRAINT `fk_usuario_usuarioopcionmenu` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO_SORTEO
-- ----------------------------
ALTER TABLE `TB_USUARIO_SORTEO` ADD CONSTRAINT `fk_usuario_usuariosorteo` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_SORTEO` ADD CONSTRAINT `fk_sorteo_usuariosorteo` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 


-- ----------------------------
-- Foreign Keys structure for table TB_USUARIO_SORTEO_ITEM
-- ----------------------------
ALTER TABLE `TB_USUARIO_SORTEO_ITEM` ADD CONSTRAINT `fk_item_usuariosorteoitem` FOREIGN KEY (`ID_ITEM`) REFERENCES TB_ITEM (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_SORTEO_ITEM` ADD CONSTRAINT `fk_sorteo_usuariosorteoitem` FOREIGN KEY (`ID_SORTEO`) REFERENCES TB_SORTEO (`ID_SORTEO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

ALTER TABLE `TB_USUARIO_SORTEO_ITEM` ADD CONSTRAINT `fk_usuario_usuariosorteoitem` FOREIGN KEY (`ID_USUARIO`) REFERENCES TB_USUARIO (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
 

